# Generated by Django 2.2.1 on 2019-06-01 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('started', models.DateField()),
                ('length', models.TextField()),
                ('context', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Context')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('done', models.DateField()),
                ('executor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='executing_requirements', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='managing_requirements', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_requirements', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.Step')),
            ],
        ),
        migrations.AddField(
            model_name='context',
            name='current_step',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preforming_contexts', to='api.Step'),
        ),
    ]
