# Generated by Django 2.2.1 on 2019-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='length',
            field=models.IntegerField(),
        ),
    ]
