# Generated by Django 2.2.1 on 2019-06-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190602_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('file', 'File'), ('checkbox', 'Condition'), ('text', 'Text')], max_length=16),
        ),
    ]
