# Generated by Django 2.2.1 on 2019-06-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190602_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='done',
            field=models.DateField(default=None, null=True),
        ),
    ]
