# Generated by Django 2.2.1 on 2019-06-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190602_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='current_step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preforming_contexts', to='api.Step'),
        ),
    ]
