# Generated by Django 2.2.1 on 2019-06-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190602_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='started',
            field=models.DateField(default=None, null=True),
        ),
    ]
