# Generated by Django 2.2.1 on 2019-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190602_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='started',
            field=models.DateField(default=None, null=True),
        ),
    ]
