# Generated by Django 2.2.1 on 2019-06-01 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_context_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='context',
        ),
        migrations.AddField(
            model_name='context',
            name='initial_step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Step'),
        ),
        migrations.AddField(
            model_name='step',
            name='next_step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Step'),
        ),
        migrations.AlterField(
            model_name='context',
            name='current_step',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Step'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='executor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
