# Generated by Django 2.2.1 on 2019-06-01 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190602_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='current_step',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Step'),
        ),
    ]
