# Generated by Django 2.2.1 on 2019-06-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190602_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context',
            name='current_step',
        ),
    ]
