# Generated by Django 2.2.1 on 2019-06-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_context_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='next_step',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_step', to='api.Step'),
        ),
    ]
