# Generated by Django 2.2.1 on 2019-06-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190602_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='receiver',
        ),
    ]
