# Generated by Django 2.2.2 on 2019-06-03 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_remove_requirement_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='manager',
        ),
        migrations.AddField(
            model_name='step',
            name='executor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
