# Generated by Django 2.2.2 on 2019-06-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190603_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='length',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='started',
            new_name='start_date',
        ),
    ]
