# Generated by Django 2.2.2 on 2019-06-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190603_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='context',
            old_name='started',
            new_name='start_date',
        ),
    ]
